CREATE TABLE IF NOT EXISTS LIBRARYUSER(ID VARCHAR PRIMARY KEY NOT NULL,
    USERNAME VARCHAR UNIQUE NOT NULL,
    PASSWORD VARCHAR NOT NULL);

CREATE TABLE IF NOT EXISTS BOOK(ID VARCHAR PRIMARY KEY NOT NULL,
    TITLE VARCHAR NOT NULL,
    AUTHOR VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    USERNAME VARCHAR NOT NULL);
